"new": QKeySequence.New
"open": QKeySequence.Open
"save": QKeySequence.Save
"save as": QKeySequence.SaveAs
"close": QKeySequence.Close
"add videos": 
"next video": QKeySequence.Forward
"prev video": QKeySequence.Back
"goto frame": Qt.CTRL + Qt.Key_J
"mark frame": Qt.CTRL + Qt.Key_M
"goto marked": Qt.CTRL + Qt.SHIFT + Qt.Key_M
"add instance": Qt.CTRL + Qt.Key_A
"delete instance": Qt.CTRL + Qt.Key_Backspace
"delete track": Qt.CTRL + Qt.SHIFT + Qt.Key_Backspace
"transpose": Qt.CTRL + Qt.Key_T
"select next": QKeySequence(Qt.Key.Key_QuoteLeft)
"clear selection": QKeySequence(Qt.Key.Key_Escape)
"goto next": Qt.CTRL + Qt.Key_Period
"goto prev": 
"goto next user": Qt.CTRL + Qt.Key_Greater
"goto next suggestion": QKeySequence.FindNext
"goto prev suggestion": QKeySequence.FindPrevious
"goto next track": Qt.CTRL + Qt.Key_E
"show labels": Qt.CTRL + Qt.Key_Tab
"show edges": Qt.CTRL + Qt.SHIFT + Qt.Key_Tab
"show trails": 
"color predicted": 
"fit": Qt.CTRL + Qt.Key_Equal
"learning": Qt.CTRL + Qt.Key_L
"export clip":
"delete clip":
"delete area": Qt.CTRL + Qt.Key_K
